# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 15:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hdcrm', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2017, 10, 6, 15, 6, 5, 622313, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
