# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdcrm', '0005_auto_20171006_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerband',
            name='thickness',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
