# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hdcrm', '0007_auto_20171007_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerband',
            name='id',
        ),
        migrations.RemoveField(
            model_name='powerband',
            name='product',
        ),
        migrations.AddField(
            model_name='powerband',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hdcrm.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
