# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hdcrm', '0012_sku_skuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skuitem',
            name='user',
        ),
    ]
