# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdcrm', '0013_remove_skuitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
