# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdcrm', '0014_sku_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='currency',
            field=models.CharField(choices=[('USD', '美金'), ('CNY', '人民币')], default='CNY', max_length=5),
        ),
    ]
