# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdcrm', '0015_sku_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='suggested_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
    ]
