# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdcrm', '0016_auto_20171010_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='skuitem',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
