# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hdcrm', '0018_auto_20171011_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('hdcrmuserinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hdcrm.HdcrmUserInfo')),
                ('mark', models.CharField(max_length=1, unique=True)),
            ],
            bases=('hdcrm.hdcrmuserinfo',),
        ),
        migrations.AddField(
            model_name='hdcrmuserinfo',
            name='type',
            field=models.CharField(choices=[('SALES', '销售员'), ('BUYER', '采购员'), ('TONGJI', '统计员'), ('ADMIN', '主管')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
