# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hdcrm', '0019_auto_20171011_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hdcrm.Sales'),
        ),
    ]
