# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hdcrm', '0020_auto_20171011_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sales',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hdcrm.Sales'),
            preserve_default=False,
        ),
    ]
