# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hdcrm', '0021_auto_20171011_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(choices=[('RMB', 'RMB'), ('USD', 'USD')], default='RMB', max_length=5)),
                ('deliveryDate', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hdcrm.Client')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hdcrm.Sales')),
            ],
        ),
        migrations.CreateModel(
            name='ContractSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=0)),
                ('unitcost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hdcrm.Contract')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hdcrm.Sku')),
            ],
        ),
        migrations.CreateModel(
            name='ContractStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INIT', '草稿'), ('SUBMIT', '提交'), ('APPROVED', '批准'), ('REJECT', '未被批准')], default='INIT', max_length=15)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hdcrm.Contract')),
            ],
        ),
        migrations.AlterField(
            model_name='hdcrmuserinfo',
            name='type',
            field=models.CharField(choices=[('SALES', '销售员'), ('BUYER', '采购员'), ('TONGJI', '统计员'), ('CAOZUOYUAN', '操作员'), ('ADMIN', '主管')], max_length=10),
        ),
    ]
