# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hdcrm', '0026_auto_20171017_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(choices=[('RMB', 'RMB'), ('USD', 'USD')], default='RMB', max_length=5)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hdcrm.Contract')),
            ],
        ),
    ]
