# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hdcrm', '0027_contractincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractincome',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
