# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hdcrm', '0031_latexband_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractstatus',
            name='contract',
        ),
        migrations.DeleteModel(
            name='ContractStatus',
        ),
    ]
