# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdcrm', '0032_auto_20171019_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('POWERBAND208', '208圈'), ('POWERBAND101', '101圈'), ('5060MINIBAND', '50/60cm小圈'), ('CAIGOU', '外购件'), ('LATEXBAND', '乳胶片'), ('OTHERLATEX', '其他乳胶制品'), ('OTHERS', '其他产品'), ('PVC', 'PVC类')], max_length=100),
        ),
    ]
