# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donwoo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
