# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import donwoo.sku_models


class Migration(migrations.Migration):

    dependencies = [
        ('donwoo', '0002_sku_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=100)),
                ('file', models.ImageField(upload_to=donwoo.sku_models.sku_upload_to)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donwoo.Sku')),
            ],
        ),
        migrations.AlterField(
            model_name='skuimage',
            name='image',
            field=models.ImageField(upload_to=donwoo.sku_models.sku_upload_to),
        ),
    ]
