# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donwoo', '0003_auto_20171022_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='skufile',
            name='filetype',
            field=models.CharField(default='', max_length=20),
        ),
    ]
