# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donwoo', '0005_auto_20171022_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skuimage',
            name='sku',
        ),
        migrations.AddField(
            model_name='skufile',
            name='filename',
            field=models.CharField(default='####', max_length=100),
        ),
        migrations.DeleteModel(
            name='SkuImage',
        ),
    ]
