# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donwoo', '0006_auto_20171022_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specs', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donwoo.Sku')),
            ],
        ),
    ]
